# Generated by Django 4.0.4 on 2022-07-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraf_name', models.CharField(max_length=100)),
                ('paragraf_content', models.CharField(max_length=10000)),
            ],
        ),
    ]
