# Generated by Django 4.0.4 on 2022-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraf_name', models.CharField(help_text='название блока', max_length=100)),
                ('paragraf_content', models.TextField(help_text='текст блока')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
