# Generated by Django 4.0.4 on 2022-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parity', '0002_block_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='position',
            field=models.IntegerField(default=0, help_text='позиция на странице относительно начала'),
        ),
    ]
