# Generated by Django 4.0.4 on 2022-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parity', '0003_block_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='position',
            field=models.IntegerField(blank=True, default=0, help_text='позиция на странице относительно начала'),
        ),
    ]
