# Generated by Django 4.1.5 on 2023-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="reed_solomon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="позиция на странице относительно начала",
                    ),
                ),
                (
                    "paragraf_name",
                    models.CharField(help_text="название блока", max_length=100),
                ),
                ("paragraf_content", models.TextField(help_text="текст блока")),
            ],
        ),
    ]
