# Generated by Django 4.0.4 on 2022-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_hamming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=0, help_text='позиция на странице относительно начала')),
                ('paragraf_name', models.CharField(help_text='название блока', max_length=100)),
                ('paragraf_content', models.TextField(help_text='текст блока')),
            ],
        ),
    ]
