# Generated by Django 4.0.6 on 2022-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='содержимое задания')),
                ('answer', models.CharField(help_text='ответ на задание', max_length=50)),
            ],
        ),
    ]
