# Generated by Django 4.1.5 on 2023-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hamming", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
