# Generated by Django 4.1.5 on 2023-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hamming", "0003_task_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.IntegerField(default=0, help_text="уровень сложности"),
        ),
    ]
